name: Deploy to GitHub Pages

on:
  # Dispara a action toda vez que houver um push na branch main
  push:
    branches: ["main"]
  # Permite rodar a action manualmente na aba Actions do GitHub
  workflow_dispatch:

# Permissões necessárias para o GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Permite apenas um deploy simultâneo
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    name: Build Frontend
    runs-on: ubuntu-latest
    
    # A aplicação está dentro da pasta 'web'
    defaults:
      run:
        working-directory: ./web

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"
          cache-dependency-path: "./web/package-lock.json"

      - name: Install dependencies
        run: npm ci

      - name: Create env file
        run: |
          echo "${{ secrets.VITE_ENV_FILE }}" > .env.local

      - name: Build project
        run: npm run build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # O vite gera o build na pasta dist
          path: "./web/dist"

  deploy:
    name: Deploy to GitHub Pages
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
